// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU2bi44crEXvaYmw3e8eCRhSgwbwblTIY',
    appId: '1:649825261819:web:341bd5153f8f449671385e',
    messagingSenderId: '649825261819',
    projectId: 'fir-first-80820',
    authDomain: 'fir-first-80820.firebaseapp.com',
    databaseURL: 'https://fir-first-80820-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-first-80820.firebasestorage.app',
    measurementId: 'G-0PDKESV1LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FFNRXoQ4nCPf67YV5IMFQdAc6fNmSf4',
    appId: '1:649825261819:android:e21219f76bb4233571385e',
    messagingSenderId: '649825261819',
    projectId: 'fir-first-80820',
    databaseURL: 'https://fir-first-80820-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-first-80820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWgW1S9Fwr3bBpZGmcKpp49vs363jIzc',
    appId: '1:649825261819:ios:2d2803cc03e8fe7e71385e',
    messagingSenderId: '649825261819',
    projectId: 'fir-first-80820',
    databaseURL: 'https://fir-first-80820-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-first-80820.firebasestorage.app',
    iosBundleId: 'com.example.finalmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJWgW1S9Fwr3bBpZGmcKpp49vs363jIzc',
    appId: '1:649825261819:ios:2d2803cc03e8fe7e71385e',
    messagingSenderId: '649825261819',
    projectId: 'fir-first-80820',
    databaseURL: 'https://fir-first-80820-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-first-80820.firebasestorage.app',
    iosBundleId: 'com.example.finalmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU2bi44crEXvaYmw3e8eCRhSgwbwblTIY',
    appId: '1:649825261819:web:f9dc0e9477f3bd4571385e',
    messagingSenderId: '649825261819',
    projectId: 'fir-first-80820',
    authDomain: 'fir-first-80820.firebaseapp.com',
    databaseURL: 'https://fir-first-80820-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-first-80820.firebasestorage.app',
    measurementId: 'G-D21GFBY909',
  );
}
